### ISSUE TITLE
Implement Cart Functionality

### ISSUE THREAD

**Issue by khardiashab** [khardiashab/OnlineBookStore#7]
**Description:**

We need to develop the logic for managing the cart functionality in our application. Users should be able to add books to their cart, view the cart, remove items, and proceed to checkout. The cart should be user-specific, with data stored in memory or a database.

**Requirements:**

1. **Add Item to Cart** (`POST /cart`):
   - Add a book to the user's cart.
   - If the book is already in the cart, increase its quantity.
   - Update the total price, number of items, and apply any applicable discounts.
   - Ensure stock is checked before adding the book to the cart.
   - Example Request Body:
     ```json
     {
       "bookId": "123",
       "quantity": 1
     }
     ```

2. **Get Cart Details** (`GET /cart`):
   - Retrieve the current state of the user's cart, including the list of items, total price, applied discounts, and total quantity.
   - Ensure the data is consistent (i.e., if items were removed or stock was updated).
   - Example Response:
     ```json
     {
       "userId": 1,
       "totalPrice": 45.99,
       "discount": 5.00,
       "totalItems": 3,
       "itemList": [
         {
           "id": 1,
           "quantity": 2,
           "book": {
             "id": "123",
             "name": "Book Title",
             "author": "Author Name",
             "price": 15.99,
             "stock": 10,
             "category": "Fiction"
           }
         }
       ]
     }
     ```

3. **Remove Item from Cart** (`DELETE /cart/{itemId}`):
   - Allow users to remove an item from the cart by its ID.
   - Update the total price, number of items, and any discounts after the removal.
   - Handle cases where the item doesn't exist in the cart.
   - Example Response (on successful removal):
     ```json
     {
       "message": "Item removed successfully"
     }
     ```

**Tasks:**
- [ ] Implement the logic to add a book to the cart (`POST /cart`).
- [ ] Implement the logic to get cart details (`GET /cart`).
- [ ] Implement the logic to remove a book from the cart (`DELETE /cart/{itemId}`).
- [ ] Ensure all endpoints update the cart’s total price, item count, and discount accurately.
- [ ] Handle error cases such as insufficient stock or invalid item IDs.
- [ ] Implement the logic to proceed with checkout (`POST /cart/checkout`).

**Acceptance Criteria:**
- Users can add, view, and remove books from their cart.
- The cart's total price, items, and discounts are updated correctly.
- Users can successfully checkout, and stock levels are updated accordingly.
- Proper error messages are shown for invalid operations (e.g., adding an out-of-stock book).
