### ISSUE TITLE
Implement Wishlist Functionality

### ISSUE THREAD

**Issue by khardiashab** [khardiashab/OnlineBookStore#8]
**Description:**

We need to develop the logic for managing the wishlist functionality in our application. Users should be able to add books to their wishlist, view the wishlist, and remove books from it. The wishlist should be user-specific and persistent.

**Requirements:**

1. **Add Book to Wishlist** (`POST /wishlist`):
   - Allow users to add a book to their wishlist.
   - Ensure that the book is not already in the wishlist to avoid duplicates.
   - Example Request Body:
     ```json
     {
       "bookId": "123"
     }
     ```
   - Example Response:
     ```json
     {
       "message": "Book added to wishlist successfully"
     }
     ```

2. **Get Wishlist** (`GET /wishlist`):
   - Retrieve the list of books in the user's wishlist.
   - Ensure the response contains full book details for each item in the wishlist.
   - Example Response:
     ```json
     {
       "userId": 1,
       "bookList": [
         {
           "id": "123",
           "name": "Book Title",
           "author": "Author Name",
           "price": 15.99,
           "stock": 10,
           "description": "Short book description",
           "image": "book-image-url",
           "category": "Fiction"
         },
         {
           "id": "456",
           "name": "Another Book",
           "author": "Another Author",
           "price": 20.00,
           "stock": 5,
           "description": "Another book description",
           "image": "another-image-url",
           "category": "Non-fiction"
         }
       ]
     }
     ```

3. **Remove Book from Wishlist** (`DELETE /wishlist/{bookId}`):
   - Allow users to remove a specific book from their wishlist.
   - Handle cases where the book doesn't exist in the wishlist.
   - Example Response (on successful removal):
     ```json
     {
       "message": "Book removed from wishlist successfully"
     }
     ```

**Tasks:**
- [ ] Implement the logic to add a book to the wishlist (`POST /wishlist`).
- [ ] Implement the logic to get the list of books in the wishlist (`GET /wishlist`).
- [ ] Implement the logic to remove a book from the wishlist (`DELETE /wishlist/{bookId}`).
- [ ] Ensure that no duplicate books can be added to the wishlist.
- [ ] Handle error cases, such as attempting to add or remove non-existent books.

**Acceptance Criteria:**
- Users can add books to their wishlist.
- The wishlist contains only unique books, and duplicate entries are not allowed.
- Users can view the books in their wishlist, including detailed book information (name, author, price, etc.).
- Users can remove books from their wishlist.
- Proper error messages are shown for invalid operations (e.g., adding an already-existing book or removing a non-existent book).
